---
language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
env:
  - RAILS_VERSION=""
  - RAILS_VERSION="~>3.2.0"
  - RAILS_VERSION="~>3.1.0"
  - RAILS_VERSION="~>3.0.0"
  - RAILS_VERSION="~>4.0.0"
  - RAILS_VERSION="~>4.1.0"
  - RAILS_VERSION="~>4.2.0"
  - RAILS_VERSION="" MONETA_VERSION="~> 0.6.0"
  - RAILS_VERSION="" MONETA_VERSION="~> 0.7.0"
notifications:
  email:
    - sutto@sutto.net
